Enclode the command to ensure they execute togheter

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -18,4 +18,4 @@ jobs:
         run: echo "The release version is ${{ env.RELEASE_VERSION }}"
       - name: Verify the release version format.
         run: |
-          echo ${{ env.RELEASE_VERSION }} | grep -E '^[0-9]+(\.[0-9]+){2}$' >/dev/null && echo "The release version has correct format." || echo "Invalid release version format." && exit 1
+          echo ${{ env.RELEASE_VERSION }} | grep -E '^[0-9]+(\.[0-9]+){2}$' >/dev/null && echo "The release version has correct format." || (echo "Invalid release version format." && exit 1)
