Test release version pattern

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -2,7 +2,7 @@ name: Create script release
 run-name: ${{ github.actor }} started a release job.
 on: [push]
 jobs:
-  Create-Script-Release:
+  build-script-release:
     runs-on: ubuntu-latest
     steps:
       - run: echo "Job started by a ${{ github.event_name }} event."
@@ -16,3 +16,6 @@ jobs:
           echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
       - name: Echo the release version.
         run: echo "The release version is ${{ env.RELEASE_VERSION }}"
+      - name: Verify the release version format.
+        run: |
+          echo ${{ env.RELEASE_VERSION }} | grep -E '^[0-9]+(\.[0-9]+){2}$' >/dev/null && echo "The release version has correct format." || echo "Invalid release version format." && exit 1
